### ISSUE TITLE
error:from langchain.indexes import VectorstoreIndexCreator index = VectorstoreIndexCreator().from_loaders([loader])

### ISSUE THREAD

**Issue by Datamore** [sophiamyang/tutorials-LangChain#1]
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-7-ef0c8cb35605>](https://localhost:8080/#) in <module>
      1 from langchain.indexes import VectorstoreIndexCreator
----> 2 index = VectorstoreIndexCreator().from_loaders([loader])

1 frames
[/usr/local/lib/python3.9/dist-packages/langchain/document_loaders/text.py](https://localhost:8080/#) in load(self)
     15     def load(self) -> List[Document]:
     16         """Load from file path."""
---> 17         with open(self.file_path) as f:
     18             text = f.read()
     19         metadata = {"source": self.file_path}

FileNotFoundError: [Errno 2] No such file or directory: 'state_of_the_union.txt'

**Comment by sophiamyang** [comment]
Hi the 'state_of_the_union.txt' file is in the repo
https://github.com/sophiamyang/tutorials-LangChain/blob/main/state_of_the_union.txt
